config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  root 'users#pick_user'
  get 'user/signin/:id', to: 'users#sign_in', as: :user_sign_in
  resources :messages, only: [:create]
  resources :chat_rooms, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :conversations, dependent: :destroy
  has_many :users, through: :conversations
  has_many :messages

  def other_user(user)
    User
      .includes(:conversations)
      .find_by(conversations: { chat_room_id: id })
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/user.rb
class User < ApplicationRecord
  has_many :conversations, dependent: :destroy
  has_many :chat_rooms, through: :conversations
  has_many :messages, through: :chat_rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  attr_accessor :current_user

  def current_user
    @current_user ||=
      begin
        User.find_by(id: session[:user_id])
      end
  end

  def set_user(user_id)
    session[:user_id] = user_id
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = current_user.chat_rooms
  end

  def show
    @chat_room = ChatRoomDecorator.new(
      chat_room:    ChatRoom.find(chat_room_id),
      current_user: current_user
    )
  end

  private

  def chat_room_id
    params.permit(:id)[:id]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    chat_room = ChatRoom.find(strong_params[:chat_room_id])
    message   = NewMessageService.create!(
      body:      message_body,
      user:      current_user,
      chat_room: chat_room
    )
    ChatChannel.broadcast_to(
      chat_room,
      message: {
        body: message.body,
        current_user: message.user.name,
        chat_room: chat_room
      }
    )
  end

  private

  def strong_params
    params.permit(:chat_room_id, :current_user_id)
  end

  def message_body
    params.require(:message).permit(:body)[:body]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def pick_user
    @users = User.all
  end

  def sign_in
    set_user(user_id)
    redirect_to chat_rooms_path
  end

  private

  def user_id
    params.permit(:id)[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat_rooms/index.html.erb
<% @chat_rooms.each do |chat_room| %>
  <%= link_to("Chat with #{chat_room.other_user(@current_user).name}", chat_room_path(chat_room.id)) %>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.title %></h1>

<div class="messages" data-chat-room-id=<%= @chat_room.id %>>
  <% @chat_room.messages.each do |message| %>
      <p class="align-<%= message.user.id == @current_user.id ? 'right' : 'left' %>"> <%= message.body %>  --  <%= message.user.name %> </p>
  <% end %>
</div>

<%= form_with(model: Message, url: messages_path, method: :post, html: { class: 'post-message' }, remote: true) do |f| %>
  <%= f.text_field :body %>
  <%= hidden_field_tag(:chat_room_id, @chat_room.id) %>
  <%= hidden_field_tag(:current_user_id, @chat_room.current_user_id) %>
  <%= submit_tag("send") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuildChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/pick_user.html.erb
<% @users.each do |user| %>
  <%= link_to(user.name, user_sign_in_path(user.id)) %>
<% end %>